services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - open-webui
      - searxng
    networks:
      - app-net

  open-webui:
    build:
      context: ./open-webui
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=/open-webui/
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_URL_PREFIX=/open-webui
    env_file:
      - .env
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - app-net

  ollama:
    image: ollama/ollama:0.1.44
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-net

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=http://localhost/searxng/
    env_file:
      - .env
    volumes:
      - searxng_data:/etc/searxng
    networks:
      - app-net

volumes:
  open-webui_data:
  ollama_data:
  searxng_data:

networks:
  app-net:
    driver: bridge
