version: '3.8'

services:
  # Redis - Cache para SearxNG
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-network

  # SearxNG - Meta-mecanismo de busca privado
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:${SEARXNG_PORT:-8080}/
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        limits:
          memory: ${SEARXNG_MAX_MEMORY:-512m}

  # Ollama - Servidor de modelos de IA local
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
      - /dev/shm:/dev/shm
    environment:
      - OLLAMA_ORIGINS=${OLLAMA_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - OLLAMA_HOST=${OLLAMA_HOST:-0.0.0.0}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-24h}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-2}
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        limits:
          memory: ${OLLAMA_MAX_MEMORY:-4g}

  # Open Web UI - Interface web para Ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPEN_WEBUI_PORT:-3000}:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_NAME=${WEBUI_NAME:-Open Web UI Local}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-pt-BR}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-true}
      - ENABLE_LOGIN_FORM=${ENABLE_LOGIN_FORM:-true}
      - ENABLE_WEB_SEARCH=${ENABLE_WEB_SEARCH:-true}
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      - TZ=${TZ:-America/Sao_Paulo}
    depends_on:
      - ollama
      - searxng
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        limits:
          memory: ${WEBUI_MAX_MEMORY:-1g}

volumes:
  ollama_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${OLLAMA_DATA_PATH:-./data/ollama}
  open_webui_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEBUI_DATA_PATH:-./data/webui}
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REDIS_DATA_PATH:-./data/redis}

networks:
  ai-network:
    driver: bridge