# Configuração otimizada do SearxNG para AutomaLLama
# Este arquivo deve ser colocado em: searxng/settings.yml

use_default_settings: true

general:
  debug: false
  instance_name: "AutomaLLama Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 2
  default_lang: "pt-BR"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    # Tempos de suspensão em caso de falha
    - 86400    # 1 dia
    - 259200   # 3 dias
    - 604800   # 7 dias
    - 2592000  # 30 dias
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "__SEARXNG_SECRET__"  # Será substituída automaticamente
  base_url: false
  image_proxy: true
  http_protocol_version: "1.1"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: redis://redis:6379/0

ui:
  static_use_hash: false
  default_locale: "pt-BR"
  query_in_title: true
  infinite_scroll: false
  center_alignment: false
  cache_url: true
  search_on_category_select: true
  hotkeys: default
  theme_args:
    simple_style: auto

# Configurações detalhadas de mecanismos de busca
engines:
  # Mecanismos de busca geral
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: false
    disabled: false
    
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
    
  - name: duckduckgo
    engine: duckduckgo
    no_cache: true
    shortcut: ddg
    disabled: false
    
  - name: startpage
    engine: startpage
    shortcut: sp
    timeout: 6.0
    disabled: false
    
  - name: searx
    engine: searx
    shortcut: se
    base_url: 'https://searx.be/'
    disabled: true
    
  # Busca de imagens
  - name: google images
    engine: google_images
    shortcut: goi
    disabled: false
    
  - name: bing images
    engine: bing_images
    shortcut: bii
    disabled: false
    
  - name: unsplash
    engine: unsplash
    shortcut: us
    disabled: false
    
  # Notícias
  - name: google news
    engine: google_news
    shortcut: gon
    disabled: false
    
  - name: bing news
    engine: bing_news
    shortcut: bin
    disabled: false
    
  # Redes sociais
  - name: reddit
    engine: reddit
    shortcut: re
    page_size: 25
    disabled: false
    
  - name: twitter
    engine: twitter
    shortcut: tw
    disabled: true  # Pode ter problemas de rate limit
    
  # Desenvolvimento e IT
  - name: github
    engine: github
    shortcut: gh
    disabled: false
    
  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false
    
  - name: gitlab
    engine: gitlab
    shortcut: gl
    disabled: false
    
  # Conhecimento e referência
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'
    number_of_results: 10
    disabled: false
    
  - name: wikidata
    engine: wikidata
    shortcut: wd
    timeout: 10.0
    disabled: false
    
  # Vídeos
  - name: youtube
    engine: youtube_noapi
    shortcut: yt
    disabled: false
    
  - name: vimeo
    engine: vimeo
    shortcut: vm
    disabled: false
    
  # Mapas
  - name: openstreetmap
    engine: openstreetmap
    shortcut: osm
    disabled: false
    
  # Arquivos e documentos
  - name: internet archive
    engine: internet_archive
    shortcut: ia
    timeout: 15.0
    disabled: false
    
  # Ciência
  - name: arxiv
    engine: arxiv
    shortcut: arx
    disabled: false
    
  - name: pubmed
    engine: pubmed
    shortcut: pub
    timeout: 10.0
    disabled: false
    
  # Música
  - name: spotify
    engine: spotify
    shortcut: spot
    api_client_id: # Deixar vazio se não tiver
    api_client_secret: # Deixar vazio se não tiver
    disabled: true
    
  # E-commerce (desabilitados por padrão)
  - name: amazon
    engine: amazon
    shortcut: az
    disabled: true
    
  # Torrents (desabilitados por questões legais)
  - name: piratebay
    engine: piratebay
    shortcut: tpb
    disabled: true

# Configurações de categorias
categories_as_tabs:
  general:
    - google
    - bing
    - duckduckgo
    - startpage
  
  images:
    - google images
    - bing images
    - unsplash
  
  videos:
    - youtube
    - vimeo
  
  news:
    - google news
    - bing news
  
  social:
    - reddit
  
  map:
    - openstreetmap
  
  it:
    - github
    - stackoverflow
    - gitlab
  
  science:
    - arxiv
    - pubmed
    - wikipedia
  
  files:
    - internet archive

# Configurações de resultado por categoria
category_default:
  general:
    - google
    - bing
    - duckduckgo
  images:
    - google images
    - bing images
  videos:
    - youtube
  news:
    - google news
  social:
    - reddit
  it:
    - github
    - stackoverflow

# Localização e idioma
locales:
  pt: Português
  pt-BR: Português (Brasil)
  en: English
  es: Español

# Configurações de cache
outgoing:
  request_timeout: 10.0
  max_request_timeout: 60.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true