use_default_settings: true
server:
  secret_key: "539fb34cf5e697a177701af89a14a72bf2343e89c1c23469947245a6e08fd8ee"
  limiter: false
  image_proxy: true
  
search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "pt-BR"
  
engines:
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: bing
    disabled: false
  - name: wikipedia
    disabled: false
  - name: github
    disabled: false

outgoing:
  request_timeout: 3.0
  max_request_timeout: 6.0
